### ISSUE TITLE
Performance difference between babylon.js and babylon.max.js

### ISSUE THREAD

**Issue by rahulchaphalkar** [BabylonJS/Samples#10]
Is there supposed to be a performance gap when switching between babylon.max.js and babylon.js ? I tried switching between them in a couple of demos, but didn't observe any performance change. (Planning on using babylon.max.js as it is more readable).
Thanks.

**Comment by deltakosh** [comment]
No difference at all. Only size is different

**Comment by rahulchaphalkar** [comment]
Thank you.
