### ISSUE TITLE
How to run the SponzaDynamicShadows demo?

### ISSUE THREAD

**Issue by juj** [BabylonJS/Samples#8]
New to Babylon.js, I'm trying to run the SponzaDynamicShadows demo, with the following attempt:

    git clone https://github.com/BabylonJS/Samples.git
    cd Samples
    python -m SimpleHTTPServer
    # navigate browser to http://localhost:8000/Demos/SponzaDynamicShadows/

However, this gives me the following errors in the web console:

	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Demos/SponzaDynamicShadows/ HTTP/1.1" 200 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /css/index.css HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /babylon.js HTTP/1.1" 200 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Demos/SponzaDynamicShadows/demo.js HTTP/1.1" 200 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /js/loader.js HTTP/1.1" 200 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/CamTouchOff.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/CamDeviceOff.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/CamGamepadJoy.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/CamVirtualJoy.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/CamAnaGly.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:39] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:39] "GET /Assets/camera.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/CamTouchOff.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/CamDeviceOff.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/CamGamepadJoy.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/CamVirtualJoy.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/camera.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Assets/CamAnaGly.png HTTP/1.1" 404 -
	127.0.0.1 - - [02/Mar/2016 13:10:40] code 404, message File not found
	127.0.0.1 - - [02/Mar/2016 13:10:40] "GET /Scenes/SponzaDynamicShadows/SponzaDynamicShadows.babylon HTTP/1.1" 404 -

The browser is then stuck at the spinning loading screen, and there is a JSON error `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 babylon.js:13:25158` that is probably a fallout of the missing file.

Searching the repository tree, I can't locate the files, especially `/Scenes/SponzaDynamicShadows/SponzaDynamicShadows.babylon`.

When I run the file `Samples/Demos/SponzaDynamicShadows/index.html` via file:/// URL, I do see the star particle trail moving around what appears otherwise a blank canvas.

Sorry if I'm missing something obvious, I was unable to find the steps to how to run this demo. Could someone help me get the demo running? What I am looking for is to run an offline/locally hosted copy of http://www.babylonjs.com/demos/SponzaDynamicShadows/. Thanks!

**Comment by deltakosh** [comment]
Ouch:) I missed this file :) Should be good now
