### ISSUE TITLE
Cannot run demos from local drive

### ISSUE THREAD

**Issue by rahulchaphalkar** [BabylonJS/Samples#9]
There are a couple of demos, which run only when opened via the URL, but not after cloning the repo to the local drive.
Example: 
http://www.babylonjs.com/Demos/MANSION/   runs successfully, however, the locally stored copy of the MANSION does not produce any graphics in Edge and FF Nightly at least (stops at loading page with black background).
Same thing for SIMD demo happens with Edge (however it runs from the local storage in Nightly, Chrome etc).

**Comment by deltakosh** [comment]
Are you deploying them to a local web server? This is mandatory for these demos;)

**Comment by rahulchaphalkar** [comment]
Thanks @deltakosh that worked. Closing issue.
